config/routes.rb
Rails.application.routes.draw do
  
		resources :customers 
		resources :transactions
#               resources :customers, except: [:show]  
		get '/splashpage/splashpage', to: 'splashpage#splashpage'
		get '/customers/:temp_id', to: 'transactions#indextran'

		namespace :api do
			resources :transactions, only: [:index]
			resources :balance, only: [:balance]
		end 								 
#  match 'v:api/*path', :to => redirect("/api/v2/%{path}")
#  get '*path', :to => redirect("/v1/%{path}")
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :transactions 
	validates :custid, presence: true 
	validates :custname, presence: true 
  	validates :custemail, presence: true 
  	validates :custgmail, presence: true
	validates :custid, uniqueness: {case_sensitive: false} 
	validates :custemail, uniqueness: {case_sensitive: false}
	validates :custgmail, uniqueness: {case_sensitive: false}
end

app/models/transaction.rb
class Transaction < ApplicationRecord

  #belongs_to :customer
  validates_uniqueness_of :tranref, :scope => :custref
  validates :custref, presence: true 
  validates :tranref, presence: true 
  validates :trandate, presence: true 
  validates :tranamount, presence: true 
end

app/models/transaction_backup.rb
class Transaction < ApplicationRecord

  belongs_to :customer
  validates_uniqueness_of :tranref, :scope => :custref
  validates :custref, presence: true 
  validates :tranref, presence: true 
  validates :trandate, presence: true 
  validates :tranamount, presence: true 
end

app/models/transaction_brake_dep.rb
class Transaction < ApplicationRecord

  #belongs_to :customer
  validates_uniqueness_of :tranref, :scope => :custref
  validates :custref, presence: true 
  validates :tranref, presence: true 
  validates :trandate, presence: true 
  validates :tranamount, presence: true 
end

app/models/versionnumber.rb
class Versionnumber < ApplicationRecord
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::API
end

app/controllers/api/transactions_controller.rb
class Api::TransactionsController < ApplicationController

	def index   
		custnumber = params[:id]
		@transactions = Transaction.where(custref: custnumber) 
                render json: @transactions
	end

 
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

before_action :set_customer, only: [:show, :edit, :update, :destroy]

  
# GET /customers
  
# GET /customers.json
  
	def index
    
		@customers = Customer.all
  
	end

  
# GET /customers/1
  
# GET /customers/1.json
  
	def show
  
#            @customer = Customer.find_by(custid: params[:id])                     	     
	end

  
# GET /customers/new
  
	def new
    
		@customer = Customer.new
  
	end

  
# GET /customers/1/edit
  
	def edit
  
	end

  
# POST /customers
  
# POST /customers.json
  
	def create
	
    @customer = Customer.new(customer_params)

    
		respond_to do |format|
      
			if @customer.save
        
				format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        				
				format.json { render :show, status: :created, location: @customer }
		  
      else
 
                                format.html { render :new }
                        
        format.json { render json: @customer.errors, status: :unprocessable_entity }
                  
      end
              
    end
 
	 end

  

# PATCH/PUT /customers/1
  
# PATCH/PUT /customers/1.json
 
	 def update
   
		 respond_to do |format|
     
			 if @customer.update(customer_params)
       
			 	format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
  
		        	format.json { render :show, status: :ok, location: @customer }
   
			  else
      
				format.html { render :edit }
			
        format.json { render json: @customer.errors, status: :unprocessable_entity }
 
			  end

		 end
  
	 end

  

# DELETE /customers/1
  

# DELETE /customers/1.json
  
	def destroy

	    @customer.destroy

		    respond_to do |format|

		        format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
 
		        format.json { head :no_content }
  
	            end

            end


# SHOW ACCOUNT TRANSACTIONS
	def transactions
		redirect_to "http://localhost:3000/transactions.html"
        end 

# SHOW ACCOUNT BALANCE
	def balance
        end




 private
    
# Use callbacks to share common setup or constraints between actions.
   
	 def set_customer
	
      @customer = Customer.find(params[:id])
 
	 end

    

# Never trust parameters from the scary internet, only allow the white list through.
    

	def customer_params
		
      params.require (:customer).permit(:custid, :custname)
    
    end

end

app/controllers/splashpage_controller.rb
class SplashpageController < ApplicationController
  
	def splashpage
	     redirect_to "http://localhost:3000/customers.html"
	end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  
# before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  
# before_action :set_transaction, only: [:show, :edit, :update, :destroy, :indextrans]

  
# GET /transactions
  
# GET /transactions.json
  
#	def index   
#		@transactions = Transaction.all
#	end

  
# GET /transactions/1
 
# GET /transactions.json
  
	def index   
		custnumber = params[:id]
#		custnumber = 1
		@transactions = Transaction.where(custref: custnumber)
                @customer = Customer.find_by(custid: params[:id])  
	end

   
# GET /transactions/1.json
  
	def show
  
	end

  
# GET /transactions/new
  
	def new
    
		@transaction = Transaction.new
  
	end

  
# GET /transactions/1/edit
  
	def edit
  
	end

  
# POST /transactionss
  
# POST /accounts.json
  
	def create
    
		@transaction = Transaction.new(transaction_params)

    
		respond_to do |format|
      
			if @transaction.save
        
				format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        						format.json { render :show, status: :created, location: @transaction }
			
else
        
				format.html { render :new }
        
				format.json { render json: @transaction.errors, status: :unprocessable_entity }
      
			end
    
		end
  
	end

  
# PATCH/PUT /transactions/1
  
# PATCH/PUT /transactions/1.json
  
	def update
    
		respond_to do |format|
      
			if @transaction.update(transaction_params)
        
				format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }

        			format.json { render :show, status: :ok, location: @transaction }
		  
      else
        
				format.html { render :edit }
        
				format.json { render json: @transaction.errors, status: :unprocessable_entity }
      
			end
    
		end
  
	end

  
# DELETE /transactions/1
  
# DELETE /stansactions/1.json
  
	def destroy
  
		  @transaction.destroy
    
			respond_to do |format|
      
				format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
 
			        format.json { head :no_content }
			
end
  
	end

  

private
    # Use callbacks to share common setup or constraints between actions.
    

	def set_transaction      
		@transaction = Transaction.find(params[:id])
    
	end

    

# Never trust parameters from the scary internet, only allow the white list through.
    
	def transaction_params
      
		params.require(:transaction).permit(:custref, :tranref, :trandate, :tranamount)
    
	end

end

app/helpers/api/balance_helper.rb
module Api::BalanceHelper
end

app/helpers/api/transactions_helper.rb
module Api::TransactionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/splashpage_helper.rb
module SplashpageHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :custid %>
    <%= f.number_field :custid %>
  </div>

  <div class="field">
    <%= f.label :custname %>
    <%= f.text_field :custname %>
  </div>

  <div class="field">
    <%= f.label :custemail %>
    <%= f.text_field :custemail %>
  </div>

  <div class="field">
    <%= f.label :custgmail %>
    <%= f.text_field :custgmail %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Eagle i-Bank - Customer Administration</h1>



<table>

<thead>

    <tr>

    <th>Custid</th>

    <th>Custname</th>

    <th colspan="3"></th>

    </tr>
  
</thead>


<tbody>
    
<% custid = 1 %>
<% @customers.each do |customer| %>

    <tr>

      <td><%= customer.custid %></td>

      <td><%= customer.custname %></td><sp>
      <td><%= link_to 'Show', customer %></td>

      <td><%= link_to "Show Transactions", controller: "transactions", action: "index", id: custid %></td>
    </tr>
    
<%custid = custid+1%>
<% end %>
  
</tbody>

</table>


<br>

<%= link_to 'New Customer', new_customer_path %>


<br />
<br />
<br />
<br />

<br />
<br />
<br />
<br />


<h4>Release 1 Version 1</h4>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>


<strong>Custid:</strong>
  
<%= @customer.custid %>
</p>


<strong>Custname:</strong>
  <%= @customer.custname %>
</p>


<strong>Custemail:</strong>
  <%= @customer.custemail %>
</p>


<strong>Custgmail:</strong>
  <%= @customer.custgmail %>
</p>



<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>

<title>Eagleibank</title>


 </head>


  <body>

    <%= yield %>

  </body>

</html>

app/views/splashpage/splashpage.html.erb
<h1>EAGLE i BANK splashpage</h1>

<p>Find me in app/views/splashpage/splashpage.html.erb</p>

<p>Currently, this page is being redirected to the customer index page via the splashpage controller</p>
<p>.erb stands for embedded Ruby. So you can embedd ruby here between <%   %> brackets. e.g. </p>
<% sum=0 %>
<% for  i in 1..5 %>
<%= "#(i) " %>
<% sum = sum + 1%>
<% end %>
<p>sum is: 
<%= "#{sum}" %>

app/views/transactions/_form.html.erb
<%= form_for(transaction) do |f| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :custref %>
    <%= f.number_field :custref %>
  </div>

  <div class="field">
    <%= f.label :tranref %>
    <%= f.number_field :tranref %>
  </div>

  <div class="field">
    <%= f.label :trandate %>
    <%= f.date_select :trandate %>
  </div>

  <div class="field">
    <%= f.label :tranamount %>
    <%= f.text_field :tranamount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>


<%= render 'form', transaction: @transaction %>


<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>
<%customer = @customer %>
<h1>Eagle i-Bank - Transactions for Customer: <%= customer.custname %></h1>
<% accountbalance = 0.0 %>


<table>

<thead>
    
<tr>
      
<!--	<th>Custref</th> -->   
 	<th>Tranref</th>
      
	<th>Trandate</th>
      
	<th>Tranamount</th>
      
	<th colspan="3"></th>

</tr>
  
</thead>

  
<tbody>
    
<% @transactions.each do |transaction| %>
<tr>
        
<!--	<td><%= transaction.custref %></td>
-->
	<td><%= transaction.tranref %></td>

	<td><%= transaction.trandate %></td>

	<td><%= transaction.tranamount %></td>

<!--	<td><%= link_to 'Show', transaction %></td>
 -->
<!--	<td><%= link_to 'Edit', edit_transaction_path(transaction) %></td> -->
<!--	<td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 -->
	<% accountbalance = accountbalance + transaction.tranamount %>
</tr>
    
<% end 
 %> 
<tr>
<td></td>
<td></td>
<td>Balance:</td>
<td><%=accountbalance.to_d.truncate(2).to_f %>
</tr> 
</tbody>

</table>

<br>


<%= link_to 'Back', customers_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Custref:</strong>
 <%= @transaction.custref %>
</p>


<p>
  <strong>Tranref:</strong>
  <%= @transaction.tranref %>
</p>


<p>
  <strong>Trandate:</strong>
  <%= @transaction.trandate %>
</p>


<p>
  <strong>Tranamount:</strong>
  <%= @transaction.tranamount %>
</p>



<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>